//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppADO.NETENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empl
    {
        public int eid { get; set; }
        public string ename { get; set; }
        public int esal { get; set; }
    }
}
